services:
  discord-hms-bot:
    build: .
    container_name: discord-hms-bot
    restart: unless-stopped
    hostname: ${HOSTNAME}
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      RADARR_API_URL: ${RADARR_API_URL}
      RADARR_API_KEY: ${RADARR_API_KEY}
      SONARR_API_URL: ${SONARR_API_URL}
      SONARR_API_KEY: ${SONARR_API_KEY}
      LIDARR_API_URL: ${LIDARR_API_URL}
      LIDARR_API_KEY: ${LIDARR_API_KEY}
      BUY_ME_A_COFFEE_URL: ${BUY_ME_A_COFFEE_URL}
      BUY_ME_A_COFFEE_ICON: ${BUY_ME_A_COFFEE_ICON}
      TVDB_API_URL: ${TVDB_API_URL}
      TVDB_API_KEY: ${TVDB_API_KEY}
